language: php
dist: xenial
php:
 - 7.0
before_install:
    - echo "hhvm.php7.all=1" >> /tmp/hhvm.php.ini
    - phpenv config-add /tmp/hhvm.php.ini
script: 
 - phpunit prueba.php
# Customize when the notification emails are sent.
notifications:
 email:
 - jtrelles@espol.edu.ec
 - isamaleo@espol.edu.ec
 - mmbaque@espol.edu.ec
    on_success: always
on_failure: always
